### ISSUE TITLE
Suggestion: Return tuple for easier destructuring

### ISSUE THREAD

**Issue by mikestopcontinues** [Coly010/no-try#3]
If you return array `[res, err]`, it's a little easier to destructure because you don't have to rename the props. The consequence is that it tightens the API to expansion, though I think it would be pretty unlikely to find anything else the function would reasonably return.

In any case, this is a great project! Thanks!

**Comment by Coly010** [comment]
I had been considering this. I was trying to work out if I could support both object destructuring and array destructuring, to allow for backwards compatibility.

I'll give it a little thought and if I can't, I'll release V2 to signify the breaking change of it returning a tuple.

**Comment by mikestopcontinues** [comment]
Very cool! Thanks!

**Comment by Coly010** [comment]
@mikestopcontinues should be good to use this as a tuple now :)

```ts
import { noTry, noTryAsync } from 'no-try/tuple'

const [result, error] = noTry(() => {
    return 12;
});
```

**Comment by mikestopcontinues** [comment]
Thanks, man! I've got a ton of code I can clean up in the morning. :)

**Comment by Coly010** [comment]
If you run into any issues, let me know!

**Comment by mikestopcontinues** [comment]
Remember when destructuring, you can still do `[, res]`, so it doesn't enforce handling errors as strongly, but I like this proposal.

**Comment by Coly010** [comment]
Interesting. I also like the `[err, res]` however, to make this change and to make array destructuring default, it would mean a breaking change. 
The library follows semver, so it shouldn't cause an issue for any codebases using the lib if they have it set up correctly in their package.json.

@paramaggarwal  I'm open to a PR if you want to submit one?

**Comment by paramaggarwal** [comment]
Nice! Thank you for being open to this, I'll get back with a PR soon.

Also, what are your thoughts on dropping the object-destructuring approach completely? I think with React Hooks also following the tuple approach, this library can take a firm opinionated stance for the tuple approach.
